# Generated by Django 5.0.7 on 2024-07-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=100)),
                ('data', models.DateField()),
                ('foto', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
