# Generated by Django 5.1 on 2024-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='poster',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='filmes/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='poster',
            field=models.ImageField(blank=True, max_length=200, upload_to='series/'),
        ),
    ]
