# Generated by Django 5.0.7 on 2024-07-25 23:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=250)),
                ('nota', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 0), django.core.validators.MaxValueValidator(10, 0)])),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gestao.filmes')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
