# Generated by Django 5.0.7 on 2024-07-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='nota_media',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
