# Generated by Django 5.1 on 2024-08-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_alter_filmes_poster_alter_series_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='mostrar',
        ),
    ]
