# Generated by Django 5.0.7 on 2024-08-17 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_rename_desc_filmes_sinopse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsfilmes',
            old_name='show',
            new_name='mostrar',
        ),
        migrations.RenameField(
            model_name='reviewsseries',
            old_name='show',
            new_name='mostrar',
        ),
    ]
