# Generated by Django 5.1 on 2024-08-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_remove_filmes_mostrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='nome',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='series',
            name='nome',
            field=models.CharField(max_length=40),
        ),
    ]
