# Generated by Django 5.0.7 on 2024-07-26 01:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_filmes_nota_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='avaliacoes',
            field=models.ManyToManyField(through='gestao.Reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
