# Generated by Django 5.1 on 2024-08-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_alter_filmes_nome_alter_series_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='qntdmembros',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
