# Generated by Django 5.0.7 on 2024-08-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_alter_filmes_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='sinopse',
            field=models.TextField(max_length=400),
        ),
    ]
