# Generated by Django 5.0.7 on 2024-08-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_filmes_sinopse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='sinopse',
            field=models.TextField(max_length=400),
        ),
    ]
