# Generated by Django 5.1 on 2024-08-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_alter_grupos_qntdmembros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmes',
            options={'verbose_name': 'Movie'},
        ),
        migrations.AlterModelOptions(
            name='grupos',
            options={'verbose_name': 'Group'},
        ),
        migrations.AlterModelOptions(
            name='noticias',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='reviewsfilmes',
            options={'verbose_name': 'Review - Movie', 'verbose_name_plural': 'Reviews - Movies'},
        ),
        migrations.AlterModelOptions(
            name='reviewsseries',
            options={'verbose_name': 'Review - Serie', 'verbose_name_plural': 'Reviews - Series'},
        ),
        migrations.AlterField(
            model_name='filmes',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='duracao',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='classificacao',
            field=models.CharField(choices=[('TV-Y', 'TV-Y'), ('TV-Y7', 'TV-Y7'), ('TV-Y7-FV', 'TV-Y7-FV'), ('TV-G', 'TV-G'), ('TV-PG', 'TV-PG'), ('TV-14', 'TV-14'), ('TV-MA', 'TV-MA')], max_length=20),
        ),
    ]
