# Generated by Django 5.0.7 on 2024-08-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_alter_noticias_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
