# Generated by Django 5.0.7 on 2024-08-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_alter_noticias_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='texto',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
