# Generated by Django 5.1 on 2024-08-20 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_comunidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('imagem', models.ImageField(blank=True, upload_to='grupos/')),
                ('desc', models.TextField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('dono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dono', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(related_name='membros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo',
            },
        ),
        migrations.DeleteModel(
            name='Comunidades',
        ),
    ]
