# Generated by Django 5.1 on 2024-08-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_alter_filmes_diretor_alter_series_diretor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('TV-Y', 'TV-Y'), ('TV-Y7', 'TV-Y7'), ('TV-Y7-FV', 'TV-Y7-FV'), ('TV-G', 'TV-G'), ('TV-PG', 'TV-PG'), ('TV-14', 'TV-14'), ('TV-MA', 'TV-MA')], max_length=20, null=True),
        ),
    ]
