# Generated by Django 5.0.7 on 2024-08-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_alter_noticias_data_alter_noticias_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='texto',
            field=models.TextField(max_length=300),
        ),
    ]
