# Generated by Django 5.1 on 2024-08-22 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_grupos_delete_comunidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='membros', to=settings.AUTH_USER_MODEL),
        ),
    ]
