# Generated by Django 5.0.7 on 2024-08-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_alter_noticias_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='usuario',
        ),
    ]
