# Generated by Django 5.1 on 2024-08-22 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_alter_grupos_membros'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='waitlist',
            field=models.ManyToManyField(blank=True, related_name='waitlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
