# Generated by Django 5.0.7 on 2024-08-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_remove_noticias_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='noticias/'),
        ),
    ]
