# Generated by Django 5.1 on 2024-08-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_grupos_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('Livre', 'Livre'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='filmes/'),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='sinopse',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
