# Generated by Django 5.1 on 2024-08-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_alter_filmes_classificacao_alter_filmes_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
