# Generated by Django 5.0.7 on 2024-08-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_alter_noticias_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='foto',
            field=models.ImageField(blank=True, upload_to='posters/'),
        ),
    ]
