# Generated by Django 5.1 on 2024-08-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_filmes_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmes',
            old_name='show',
            new_name='mostrar',
        ),
    ]
