# Generated by Django 5.0.7 on 2024-08-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0014_alter_filmes_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmes',
            old_name='foto',
            new_name='poster',
        ),
    ]
