# Generated by Django 5.1 on 2024-08-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0014_rename_show_filmes_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='atores',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='filmes',
            name='escritor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
