# Generated by Django 5.1 on 2024-08-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0015_filmes_atores_filmes_escritor'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='atores',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='escritor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
