# Generated by Django 5.0.7 on 2024-08-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0016_noticias_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmes',
            options={'verbose_name': 'Filme'},
        ),
        migrations.AlterModelOptions(
            name='noticias',
            options={'verbose_name': 'Noticia'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review'},
        ),
    ]
