# Generated by Django 5.0.7 on 2024-08-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0018_alter_noticias_nome_alter_noticias_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='mostrar',
            field=models.BooleanField(default=False),
        ),
    ]
