# Generated by Django 5.0.7 on 2024-08-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0020_alter_noticias_nome_alter_noticias_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='classificacao',
            field=models.CharField(choices=[('opcao1', 'Livre'), ('opcao2', '10'), ('opcao3', '12'), ('opcao4', '14'), ('opcao5', '16'), ('opcao6', '18')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmes',
            name='diretor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='filmes',
            name='duracao',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
