# Generated by Django 5.0.7 on 2024-08-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0021_filmes_classificacao_filmes_diretor_filmes_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
