# Generated by Django 5.0.7 on 2024-08-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0022_reviews_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
