# Generated by Django 5.0.7 on 2024-08-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0023_reviews_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=31)),
                ('diretor', models.CharField(max_length=31)),
                ('data_lancamento', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('episodios', models.PositiveSmallIntegerField()),
                ('temporadas', models.PositiveSmallIntegerField()),
                ('sinopse', models.TextField(max_length=200)),
                ('nota_media', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'verbose_name': 'Series',
            },
        ),
    ]
