# Generated by Django 5.0.7 on 2024-08-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0024_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Serie'},
        ),
        migrations.AddField(
            model_name='series',
            name='poster',
            field=models.ImageField(blank=True, upload_to='series/'),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='poster',
            field=models.ImageField(blank=True, upload_to='filmes/'),
        ),
    ]
