# Generated by Django 5.0.7 on 2024-08-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0025_alter_series_options_series_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
