# Generated by Django 5.0.7 on 2024-08-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0026_alter_filmes_data_alter_series_data_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='roteirista',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='diretor',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
