# Generated by Django 5.0.7 on 2024-08-14 21:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0028_remove_series_roteirista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='ReviewsFilmes',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='avaliacoes',
        ),
    ]
