# Generated by Django 5.0.7 on 2024-08-14 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0029_rename_reviews_reviewsfilmes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='avaliacoes',
            field=models.ManyToManyField(through='gestao.ReviewsFilmes', to=settings.AUTH_USER_MODEL),
        ),
    ]
