# Generated by Django 5.0.7 on 2024-08-14 21:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0030_filmes_avaliacoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewsfilmes',
            options={'verbose_name': 'Review - Filme'},
        ),
        migrations.CreateModel(
            name='ReviewsSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('review', models.TextField(max_length=250)),
                ('nota', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 0), django.core.validators.MaxValueValidator(10, 0)])),
                ('show', models.BooleanField(default=False)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gestao.series')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review - Serie',
            },
        ),
    ]
