# Generated by Django 5.0.7 on 2024-08-14 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0031_alter_reviewsfilmes_options_reviewsseries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='avaliacoes',
            field=models.ManyToManyField(through='gestao.ReviewsSeries', to=settings.AUTH_USER_MODEL),
        ),
    ]
