# Generated by Django 5.0.7 on 2024-08-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0032_series_avaliacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='data_lancamento',
            new_name='data',
        ),
    ]
